export {default as Mainpage} from './Productpage'
export {default as FavouritesProductsPage} from './FavouritePage'
export {default as SearchResults} from './SearchPage'
export {default as AddnewproductPage} from './Addproductpage'
export {default as Editproductpage} from './Editproductpage'